In [1]:
import pandas as pd

estacion = '5530E'
df = pd.read_csv(r'./data/'+estacion+'_clean.csv', sep=',')

In [2]:
df.columns

Index(['tmed', 'prec', 'tmin', 'tmax', 'dir', 'velmedia', 'racha', 'sol',
       'presmax', 'presmin', 'year', 'month', 'day', 'rain_today',
       'rain_tomorrow', 'horatmin_', 'horatmax_', 'horaracha_',
       'horapresmin_'],
      dtype='object')

In [3]:
X = df[['tmed', 'prec', 'tmin', 'tmax', 'dir', 'velmedia', 'racha', 'sol',
       'presmax', 'presmin', 'year', 'month', 'day', 'rain_today',
        'horatmin_', 'horatmax_', 'horaracha_',
       'horapresmin_']]
y = df['rain_tomorrow']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

### Preparamos el dataset

In [6]:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Creamos el Modelo

In [7]:
n_neighbors = 7

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train, y_train)

print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.87
Accuracy of K-NN classifier on test set: 0.84


In [8]:
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[738  42]
 [119  88]]
              precision    recall  f1-score   support

           0       0.86      0.95      0.90       780
           1       0.68      0.43      0.52       207

    accuracy                           0.84       987
   macro avg       0.77      0.69      0.71       987
weighted avg       0.82      0.84      0.82       987



In [11]:
import matplotlib.pyplot as plt

from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches

h = .02  # step size in the mesh

# Create color maps
cmap_light = ListedColormap(['#FFAAAA', '#ffcc99'])
cmap_bold = ListedColormap(['#FF0000', '#ff9933'])

# we create an instance of Neighbours Classifier and fit the data.
clf = KNeighborsClassifier(n_neighbors, weights='distance')
clf.fit(X, y)

# Plot the decision boundary. For that, we will assign a color to each
# point in the mesh [x_min, x_max]x[y_min, y_max].
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1 # columna 0 en x, resto y sumo 1 para verlo mejor (más margen)
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1 # columna 1 en y, resto y sumo 1 para verlo mejor (más margen)
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
Z = clf.predict(np.c_[xx.ravel(), yy.ravel()]) # predice dos columnas que tienen todas las combinaciones x-y
# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.figure()
plt.pcolormesh(xx, yy, Z, cmap=cmap_light)

# Plot also the training points
plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold,
                edgecolor='k', s=20)
plt.xlim(xx.min(), xx.max())
plt.ylim(yy.min(), yy.max())

patch0 = mpatches.Patch(color='#FF0000', label='1')
patch1 = mpatches.Patch(color='#ff9933', label='2')
plt.legend(handles=[patch0, patch1])

    
plt.title("2-Class classification (k = %i, weights = '%s')"
              % (n_neighbors, 'distance'))

plt.show()

TypeError: '(slice(None, None, None), 0)' is an invalid key

### Predicciones

In [18]:
nuevo_transformado = scaler.transform([[4.5,0.0,-2.2,11.2,35.0,3.1,10.8,7.1,957.7,954.6,2013,1,15,0,7.0,14.0,17.0,15.0]]) 

/opt/anaconda3/envs/TheBridgeBootcamp/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


In [19]:
print(clf.predict(nuevo_transformado))

[1]


/opt/anaconda3/envs/TheBridgeBootcamp/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [20]:
print(clf.predict_proba(scaler.transform([[4.5,0.0,-2.2,11.2,35.0,3.1,10.8,7.1,957.7,954.6,2013,1,15,0,7.0,14.0,17.0,15.0]])))

[[0.1429997 0.8570003]]


/opt/anaconda3/envs/TheBridgeBootcamp/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"
/opt/anaconda3/envs/TheBridgeBootcamp/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [21]:
knn = KNeighborsClassifier(n_neighbors= 7)
knn.fit(X_train, y_train)
print(knn.predict(nuevo_transformado))
print(knn.predict_proba(nuevo_transformado))

[0]
[[0.85714286 0.14285714]]


In [22]:
clf

KNeighborsClassifier(n_neighbors=7, weights='distance')

In [23]:
knn.weights

'uniform'